### ISSUE TITLE
How do you set this up on OSX?

### ISSUE THREAD

**Issue by sebastienvg** [fishythefish/Myouse#1]
I cloned the repo now what?

**Comment by thomasfinch** [comment]
If you open the repo folder, there's a folder called OS X that contains an Xcode project for the program. Connect your myo first, then just open it up in Xcode and run it on your mac, it should start working.

**Comment by sebastienvg** [comment]
Awesome, thanks for the quick reply.

-- 
Sebastien Vayrette-Gavard
Sr System Administrator | PunchLineGroup Inc.
sebastien@punchlinegroup.com | 1.905.808.6907 

On January 21, 2015 at 6:24:23 PM, Thomas Finch (notifications@github.com) wrote:

If you open the repo folder, there's a folder called OS X that contains an Xcode project for the program. Connect your myo first, then just open it up in Xcode and run it on your mac, it should start working.
